development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "dex15900122@gmail.com"
  password: "e5900123"
  enable_starttls_auto: true
  host: 'cathaybk.herokuapp.com'